In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [12]:
data=pd.read_csv('Churn_Modelling.csv')
data.head() ##EstimatedSalary will be the O/P feature (Regression problem statement)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [13]:
##Preprocess the data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [14]:
##Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [15]:
##Onehot encode 'Geography'
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
##Combine one-hot encoded columns with original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [17]:
##Split the data into features and target
x=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [18]:
##Spilt the data into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
##Scale the features
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [20]:
#Save the encoders and scaler for later use
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### ANN Regression Problem Statement

In [21]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\Niraj\Documents\ANN Classification\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [22]:
##Build the model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) ##Output layer for regression, Linear activation function is specifically for regression which is applied by default
])

##Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From c:\Users\Niraj\Documents\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\Niraj\Documents\ANN Classification\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [24]:
#Setup Early Stopping
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [25]:
#Train the model
history=model.fit(
    x_train,y_train,
    validation_data=(x_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Niraj\Documents\ANN Classification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Niraj\Documents\ANN Classification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 4ms/step - loss: 100381.9531 - mae: 100381.9531 - val_loss: 98534.3750 - val_mae: 98534.3750
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99683.9297 - mae: 99683.9297 - val_loss: 97104.7031 - val_mae: 97104.7031
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 97156.5781 - mae: 97156.5781 - val_loss: 93370.8906 - val_mae: 93370.8906
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 92133.4922 - mae: 92133.4922 - val_loss: 87085.9844 - val_mae: 87085.9844
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 84725.5234 - mae: 84725.5234 - val_loss: 78777.3203 - val_mae: 78777.3203
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 75860.7500 - mae: 75860.7500 - val_loss: 69969.0391 - val_mae: 69969.0391
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 67044.0859 - mae: 67044.0859 - val_loss: 62213.1992 - val_mae: 62213.1992
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 59808.1875 - mae: 59808.1875 - val_loss: 56435.2305 - val_mae: 56435.2305
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 54962.0898 - mae: 54962.0898 - val_loss: 53061.6211 - val_mae: 53061.6211
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 52234.0234 - mae: 52234.0234 - val_loss: 51483.0938 - val_mae: 51483.0938
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 50992.5117 - mae: 50992.5117 - val_loss: 50963.5508 - val_mae: 50963.5508
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 50487.9883 - mae: 50487.9883 - val_loss: 50763.1523 - val_mae: 50763.1523
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 50280.2461 - mae: 50280.2461 - val_loss: 50683.3516 - val_mae: 50683.3516
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50170.1094 - mae: 50170.1094 - val_loss: 50654.4766 - val_mae: 50654.4766
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 50094.5938 - mae: 50094.5938 - val_loss: 50621.0742 - val_mae: 50621.0742
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 50043.3203 - mae: 50043.3203 - val_loss: 50593.5039 - val_mae: 50593.5039
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 49997.4648 - mae: 49997.4648 - val_loss: 50565.3359 - val_mae: 50565.3359
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 49955.6289 - mae: 49955.6289 - val_loss: 50534.2148 - val_mae: 50534.2148
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 49918.7695 - mae: 49918.7695 - val_loss: 50509.1289 - val_mae: 50509.1289
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 49884.7109 - mae: 49884.7109 - val_loss: 50498.7461 - val_mae: 50498.7461
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 49855.0781 - mae: 49855.0781 - val_loss: 50477.5430 - val_mae: 50477.5430
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49829.4648 - mae: 49829.4648 - val_loss: 50468.1250 - val_mae: 50468.1250
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 49804.5508 - mae: 49804.5508 - val_loss: 50444.0742 - val_mae: 50444.0742
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49781.7734 - mae: 49781.7734 - val_loss: 50443.0469 - val_mae: 50443.0469
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49759.6602 - mae: 49759.6602 - val_loss: 50433.8281 - val_mae: 50433.8281
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49739.3398 - mae: 49739.3398 - val_loss: 50427.1367 - val_mae: 50427.1367
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49723.7070 - mae: 49723.7070 - val_loss: 50416.9805 - val_mae: 50416.9805
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49705.6875 - mae: 49705.6875 - val_loss: 50402.3906 - val_mae: 50402.3906
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49689.4492 - mae: 49689.4492 - val_loss: 50389.7852 - val_mae: 50389.7852
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49672.4336 - mae: 49672.4336 - val_loss: 50376.9727 - val_mae: 50376.9727
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49658.3516 - mae: 49658.3516 - val_loss: 50368.6016 - val_mae: 50368.6016
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49648.1289 - mae: 49648.1289 - val_loss: 50356.5430 - val_mae: 50356.5430
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49636.1484 - mae: 49636.1484 - val_loss: 50348.2305 - val_mae: 50348.2305
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49625.0859 - mae: 49625.0859 - val_loss: 50337.9102 - val_mae: 50337.9102
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49611.8750 - mae: 49611.8750 - val_loss: 50334.2852 - val_mae: 50334.2852
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49606.1562 - mae: 49606.1562 - val_loss: 50335.4336 - val_mae: 50335.4336
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49595.7227 - mae: 49595.7227 - val_loss: 50341.1953 - val_mae: 50341.1953
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49583.8477 - mae: 49583.8477 - val_loss: 50333.5547 - val_mae: 50333.5547
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49570.8828 - mae: 49570.8828 - val_loss: 50323.1523 - val_mae: 50323.1523
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49563.0312 - mae: 49563.0312 - val_loss: 50322.3164 - val_mae: 50322.3164
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49557.5234 - mae: 49557.5234 - val_loss: 50325.5859 - val_mae: 50325.5859
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 49544.6914 - mae: 49544.6914 - val_loss: 50317.2539 - val_mae: 50317.2539
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49538.1250 - mae: 49538.1250 - val_loss: 50314.7578 - val_mae: 50314.7578
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49528.9414 - mae: 49528.9414 - val_loss: 50306.9766 - val_mae: 50306.9766
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49521.3203 - mae: 49521.3203 - val_loss: 50324.5977 - val_mae: 50324.5977
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49515.4570 - mae: 49515.4570 - val_loss: 50323.7344 - val_mae: 50323.7344
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49508.0547 - mae: 49508.0547 - val_loss: 50320.1016 - val_mae: 50320.1016
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49499.4414 - mae: 49499.4414 - val_loss: 50323.0039 - val_mae: 50323.0039
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49495.1133 - mae: 49495.1133 - val_loss: 50310.5430 - val_mae: 50310.5430
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49488.1953 - mae: 49488.1953 - val_loss: 50315.6445 - val_mae: 50315.6445
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49480.1484 - mae: 49480.1484 - val_loss: 50310.8320 - val_mae: 50310.8320
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 49473.3711 - mae: 49473.3711 - val_loss: 50313.9570 - val_mae: 50313.9570
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 49467.6289 - mae: 49467.6289 - val_loss: 50318.4609 - val_mae: 50318.4609
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 49462.3555 - mae: 49462.3555 - val_loss: 50315.7852 - val_mae: 50315.7852

In [26]:
%load_ext tensorboard

In [30]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 1856), started 0:01:14 ago. (Use '!kill 1856' to kill it.)

In [31]:
##Evaluate model on test data
test_loss,test_mae=model.evaluate(x_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 976us/step - loss: 50306.9766 - mae: 50306.9766
Test MAE : 50306.9765625

In [32]:
model.save('regression_model.h5')

c:\Users\Niraj\Documents\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(